// app/api/admin/email-interview-brief/route.ts
// Sends a generated interview brief to one or more council members via Resend.
// Admin-only. Expects the brief text, candidate name, and recipient list.

import { NextRequest, NextResponse } from 'next/server'
import { requireRole } from '../../../../lib/api-auth'
import { EMAIL_FROM, ORG_NAME } from '../../../../lib/config'
import { wrapEmail } from '../../../../lib/email-templates'
import { fetchWithTimeout } from '../../../../utils/fetchWithTimeout'

function briefToHtml(briefText: string, candidateName: string): string {
  // Convert plain text brief into styled HTML sections
  const DEEP_SEA = '#00426A'
  const lines = briefText.split('\n')
  let html = ''
  const sectionHeaders = [
    'CANDIDATE OVERVIEW',
    'ASSIGNMENT COMPLETION SUMMARY',
    'COUNCIL-IDENTIFIED STRENGTHS',
    'AREAS FOR CONTINUED GROWTH',
    'SELF-ASSESSMENT INSIGHT',
    'PARDINGTON STUDY PATTERNS',
    'SUGGESTED INTERVIEW PROBES',
  ]

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) {
      html += '<br/>'
      continue
    }
    if (sectionHeaders.some(h => trimmed.toUpperCase().startsWith(h))) {
      html += `<h2 style="color:${DEEP_SEA};font-size:15px;font-weight:bold;margin:24px 0 8px;padding-bottom:6px;border-bottom:2px solid #e2e8f0;letter-spacing:0.04em;">${escapeHtml(trimmed)}</h2>`
    } else if (/^\d+[\.\)]\s/.test(trimmed) || trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
      html += `<p style="color:#334155;font-size:14px;line-height:1.7;margin:4px 0 4px 16px;padding-left:8px;border-left:3px solid #e2e8f0;">${escapeHtml(trimmed)}</p>`
    } else {
      html += `<p style="color:#334155;font-size:14px;line-height:1.7;margin:6px 0;">${escapeHtml(trimmed)}</p>`
    }
  }

  const header = `<p style="color:#64748b;font-size:12px;font-weight:bold;text-transform:uppercase;letter-spacing:0.08em;margin:0 0 4px;">AI Interview Brief</p>
<h1 style="color:${DEEP_SEA};font-size:22px;font-weight:900;margin:0 0 4px;">${escapeHtml(candidateName)}</h1>
<p style="color:#94a3b8;font-size:12px;margin:0 0 20px;">Generated ${new Date().toLocaleDateString('en-CA', { year: 'numeric', month: 'long', day: 'numeric' })} &middot; ${ORG_NAME}</p>
<hr style="border:none;border-top:1px solid #e2e8f0;margin:0 0 16px;"/>`

  const footer = `<hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0 12px;"/>
<p style="color:#94a3b8;font-size:11px;font-style:italic;margin:0;">Confidential — for council use only. Generated by AI from available portal data; exercise pastoral judgment in interpretation.</p>`

  return wrapEmail(header + html + footer)
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export async function POST(req: NextRequest) {
  const auth = await requireRole(req, 'admin')
  if (auth.error) return auth.error

  const body = await req.json().catch(() => ({}))
  const { briefText, candidateName, recipients } = body

  if (!briefText || !candidateName) {
    return NextResponse.json({ sent: false, reason: 'Missing briefText or candidateName' }, { status: 400 })
  }

  // recipients: array of { email, name? } — default to admin email if empty
  const to: string[] = Array.isArray(recipients) && recipients.length > 0
    ? recipients.map((r: any) => r.name ? `${r.name} <${r.email}>` : r.email)
    : []

  if (to.length === 0) {
    return NextResponse.json({ sent: false, reason: 'No recipients specified' }, { status: 400 })
  }

  const resendKey = process.env.RESEND_API_KEY
  if (!resendKey) {
    return NextResponse.json({ sent: false, reason: 'RESEND_API_KEY not configured' }, { status: 500 })
  }

  const html = briefToHtml(briefText, candidateName)

  const resendRes = await fetchWithTimeout('https://api.resend.com/emails', {
    method: 'POST',
    timeoutMs: 15_000,
    headers: {
      'Authorization': `Bearer ${resendKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: EMAIL_FROM,
      to,
      subject: `AI Interview Brief — ${candidateName}`,
      html,
    }),
  })

  if (!resendRes.ok) {
    const detail = await resendRes.text()
    return NextResponse.json({ sent: false, reason: 'Email delivery failed', detail }, { status: 502 })
  }

  return NextResponse.json({ sent: true, recipientCount: to.length })
}
